// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/unauthorized": {
    params: {};
  };
  "/worlds": {
    params: {};
  };
  "/worlds/:worldId": {
    params: {
      "worldId": string;
    };
  };
  "/worlds/:worldId/:export": {
    params: {
      "worldId": string;
      "export": string;
    };
  };
  "/worlds/:worldId/export/:articleId": {
    params: {
      "worldId": string;
      "articleId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/unauthorized" | "/worlds" | "/worlds/:worldId" | "/worlds/:worldId/:export" | "/worlds/:worldId/export/:articleId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/auth/login";
  };
  "routes/auth/unauthorized.tsx": {
    id: "routes/auth/unauthorized";
    page: "/auth/unauthorized";
  };
  "routes/authenticated.tsx": {
    id: "routes/authenticated";
    page: "/" | "/worlds" | "/worlds/:worldId" | "/worlds/:worldId/:export" | "/worlds/:worldId/export/:articleId";
  };
  "routes/worlds/wrapper.tsx": {
    id: "routes/worlds/wrapper";
    page: "/worlds";
  };
  "routes/worlds/index.tsx": {
    id: "routes/worlds/index";
    page: "/worlds";
  };
  "routes/worlds/$worldId/wrapper.tsx": {
    id: "routes/worlds/$worldId/wrapper";
    page: "/worlds/:worldId" | "/worlds/:worldId/:export" | "/worlds/:worldId/export/:articleId";
  };
  "routes/worlds/$worldId/index.tsx": {
    id: "routes/worlds/$worldId/index";
    page: "/worlds/:worldId";
  };
  "routes/worlds/$worldId/export.tsx": {
    id: "routes/worlds/$worldId/export";
    page: "/worlds/:worldId/:export";
  };
  "routes/worlds/$worldId/$articleId.tsx": {
    id: "routes/worlds/$worldId/$articleId";
    page: "/worlds/:worldId/export/:articleId";
  };
};