// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/authenticated": {
    params: {};
  };
  "/authenticated/worlds/:worldId": {
    params: {
      "worldId": string;
    };
  };
  "/authenticated/worlds/:worldId/export": {
    params: {
      "worldId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/authenticated" | "/authenticated/worlds/:worldId" | "/authenticated/worlds/:worldId/export";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/auth/login";
  };
  "routes/authenticated.tsx": {
    id: "routes/authenticated";
    page: "/authenticated" | "/authenticated/worlds/:worldId" | "/authenticated/worlds/:worldId/export";
  };
  "routes/authenticated/home.tsx": {
    id: "routes/authenticated/home";
    page: "/authenticated";
  };
  "routes/authenticated/worlds/$worldId/details.tsx": {
    id: "routes/authenticated/worlds/$worldId/details";
    page: "/authenticated/worlds/:worldId";
  };
  "routes/authenticated/worlds/$worldId/export.tsx": {
    id: "routes/authenticated/worlds/$worldId/export";
    page: "/authenticated/worlds/:worldId/export";
  };
};