import type { ArticleResponse, CharacterSheet } from "shared/types/worldAnvilTypes";

export const mockArticle: ArticleResponse = {
  id: "2490bf16-bc70-4de5-9634-5e7d8a227850",
  title: "Example Earl of Handsome Sheet March 2023 Run",
  slug: "example-earl-of-handsome-sheet-march-2023-run-article",
  state: "private",
  isWip: true,
  isDraft: false,
  entityClass: "Article",
  icon: "fas fa-solid fa-file-user",
  url: "https://www.worldanvil.com/w/lies-26-liability-grimmoireproductions/a/example-earl-of-handsome-sheet-march-2023-run-article",
  subscribergroups: [
    {
      id: "8e6ec8c6-eb4b-4bcc-ab8a-c8b58c623ca9",
      title: "L&L Staff",
      slug: null,
      state: null,
      entityClass: "SubscriberGroup",
      icon: null,
      url: null,
      subscribergroups: [],
    },
  ],
  folderId: "-1",
  tags: "example,character_sheet",
  updateDate: {
    date: "2025-07-03 18:55:15.000000",
    timezone_type: 3,
    timezone: "Europe/London",
  },
  position: null,
  excerpt: null,
  wordcount: 773,
  creationDate: {
    date: "2023-11-11 06:06:19.000000",
    timezone_type: 3,
    timezone: "Europe/London",
  },
  publicationDate: {
    date: "2023-11-11 06:26:07.000000",
    timezone_type: 3,
    timezone: "Europe/London",
  },
  notificationDate: null,
  likes: null,
  views: 4,
  userMetadata: null,
  articleMetadata: null,
  cssClasses: null,
  displayCss: null,
  templateType: "article",
  customArticleTemplate: {
    id: "fab3a595-aa68-47c6-8d11-8f5f7df3db76",
    title: "Player-Facing Character Sheet (L&L)",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "CustomArticleTemplate",
    icon: "fas fa-solid fa-file-user",
    url: null,
    subscribergroups: [],
    folderId: null,
    tags: "character_sheet",
    updateDate: null,
  },
  editor: "code",
  content:
    "[img:5090045]\r\n[container: name]\r\n[h1]The Earl of Handsome, Sylvester Goodlooks[/h1]\r\n[/container]\r\n[container: subtitle]\r\n[p]Recently widowed duke looking for a second chance at love; 45 years-of-age; Inspired by Protagonist Lastname from Popular Regency Novel[/p]\r\n[/container]\r\n[hr]\r\n[container:mycvvsf]\r\n[p]“My [b]Character[/b] is charming and dutiul.”[/p]\r\n[p]“My [b]Virtues[/b] are many. I am kind to those who work for me, and I have a strong sense of duty.”[/p]\r\n[p]“My [b]Vices[/b] are few. I’m prone to introversion, and often get lost in my work and fail to maintain relationships.”[/p]\r\n[p]“My [b]Situation[/b] is extremely well off. I am in possession of a Large Fortune and I always make sound investments..”[/p]\r\n[p]“My [b]Family[/b] is of the highest standing. The Goodlooks are a well respected line of nobility that dates back centuries. We are one of the more influential families at court.”[/p]\r\n[/container]\r\n[hr]\r\n[container:summary]\r\n[p]You've always known to put duty before self. You were groomed for your father's title for a young age, and you did everything exactly right. You've always been attractive, so finding a wife that met your father's expectations wasn't difficult, and while you were never madly in love with the late @[[b]Lady Handsome[/b]](person:7ad8756d-6e48-4a48-afcd-6016cf95c70e), you grew to love her in your own way over the years and honestly mourned her death. As much as you grieve her loss, you can't help but feel anticipation for the opportunity this has presented to find a true companion to live out the rest of your years with. A woman of [i]your[/i] dreams, not your father's. Your fifteen year old son is something of a rake in the making, in spite of your best efforts. Perhaps maternal influence would do him good.\r\n[/p]\r\n[/container]\r\n[container:plots]\r\n[h2]Pithy section title one[/h2]\r\n@[Plot: Example Plot page](plot:7430dcce-22f3-426d-a8e8-60912a450536)\r\n[p]Lorem ipsum @[necklace](item:56f0f627-5e0d-4c29-b784-d6c72d5fac28) dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.[sup]1[/sup] Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. [var:ton-grimmoireproductions][/p]\r\n[h2]Pithy section header for another plot[/h2]\r\n@[Plot: Example Plot page](plot:7430dcce-22f3-426d-a8e8-60912a450536)\r\n[p]Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, the @[British Army](organization:e87de440-1658-448e-a296-2038f9225bbf) totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, @cambr qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?[sup]2[/sup] Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?[/p]\r\n[/container]\r\n[container:alittlebirdtoldme]\r\n[h2]A Little Bird Told Me...[/h2]\r\n[secret:cff9ed00-52e0-4d42-8957-eac8ac2097c8]\r\n[secret:cff9ed00-52e0-4d42-8957-eac8ac2097c8]\r\n[/container]\r\n[hr]\r\n[container:skillsSecretsWishes]\r\n[p]“I have a number of [b]skills[/b]. I am charismatic and compassionate, and I am generally able to convince people to my point of view. I am well-trained in business, and make sound investments.”[/p]\r\n[p]“My [b]secret[/b] is that I don't have control over my teenage son, and it's only a matter of time until he ruins some young woman unless I can get his behavior under control.”[/p]\r\n[p]“My [b]dearest wish[/b] is to find a loving partner to share my life with.”[/p]\r\n[/container]\r\n[hr]\r\n[container:stats]\r\n[p][b]Rank:[/b] 7 | [b]Scandal:[/b] 0 | [b]Aberrations:[/b] strong sense of duty[/p]\r\n[/container]\r\n[hr]\r\n[container:flavorQuote]\r\n[quote]\r\n\"Pretend this is an incredibly appropriate quote\"|Source\r\n[/quote]\r\n[/container]",
  author: {
    id: "50900790-4316-4d4c-8a27-51df0e89572e",
    title: "grimmoireproductions",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "User",
    icon: "fa-solid fa-user",
    url: "https://www.worldanvil.com/author/grimmoireproductions",
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  category: null,
  world: {
    id: "db8e5425-5c36-47e4-b003-0f48403821c6",
    title: "Lies & Liability",
    slug: "lies-26-liability-grimmoireproductions",
    state: "private",
    isWip: null,
    isDraft: null,
    entityClass: "World",
    icon: "fa-solid fa-globe-stand",
    url: "https://www.worldanvil.com/w/lies-26-liability-grimmoireproductions",
    subscribergroups: [
      {
        id: "18cac1c2-9ffa-4aeb-88d9-7071a8ae26e0",
        title: "Adventurers of Test L&L Campaign Party",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
      {
        id: "8e6ec8c6-eb4b-4bcc-ab8a-c8b58c623ca9",
        title: "L&L Staff",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
      {
        id: "9bb37b11-6923-49a8-843e-529682c05f24",
        title: "L&L Testers",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
      {
        id: "495aef44-55ba-45ea-b545-7a4dc5a4856e",
        title: "Test L&L Campaign Players",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
      {
        id: "3f57f6e5-bc33-4bae-b39f-9949e811ef21",
        title: "WinKaye",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
    ],
    folderId: "-1",
    tags: "",
    updateDate: {
      date: "2025-08-29 21:56:35.000000",
      timezone_type: 3,
      timezone: "Europe/London",
    },
  },
  cover: {
    id: -1,
    title: "Default Cover",
    slug: null,
    state: null,
    isWip: null,
    isDraft: null,
    entityClass: "Image",
    icon: "fa-solid fa-image",
    url: "https://wa-cdn.nyc3.cdn.digitaloceanspaces.com/assets/prod/prodromos-client/images/WorldCover_Default.jpg",
    subscribergroups: [],
    folderId: null,
    tags: null,
    updateDate: null,
  },
  coverSource: "World",
  pronunciation: null,
  snippet: null,
  seeded: null,
  sidebarcontent: null,
  sidepanelcontenttop: "[h2]Table of Contents[/h2]\r\n[articletoc]",
  sidepanelcontent: null,
  sidebarcontentbottom: null,
  footnotes: "[sup]1[/sup] A footnote\r\n\r\n[sup]2[/sup] Another footnote",
  fullfooter: null,
  authornotes: null,
  scrapbook: null,
  credits: null,
  displaySidebar: true,
  articleNext: null,
  articlePrevious: null,
  timeline: null,
  prompt: null,
  gallery: null,
  articleParent: {
    id: "7ad8756d-6e48-4a48-afcd-6016cf95c70e",
    title: "EXAMPLE Staff-Facing Player Character Article",
    slug: "example-staff-facing-player-character-article-person",
    state: "private",
    isWip: true,
    isDraft: false,
    entityClass: "Person",
    icon: "fas fa-solid fa-user",
    url: "https://www.worldanvil.com/w/lies-26-liability-grimmoireproductions/a/example-staff-facing-player-character-article-person",
    subscribergroups: [
      {
        id: "8e6ec8c6-eb4b-4bcc-ab8a-c8b58c623ca9",
        title: "L&L Staff",
        slug: null,
        state: null,
        entityClass: "SubscriberGroup",
        icon: null,
        url: null,
        subscribergroups: [],
      },
    ],
    folderId: "922ba051-547a-49db-8399-64c6113b4264",
    tags: "player_character,cw_example,example_pc",
    updateDate: {
      date: "2024-07-29 20:51:34.000000",
      timezone_type: 3,
      timezone: "Europe/London",
    },
  },
  block: null,
  orgchart: null,
  showSeeded: false,
  webhookUpdate: false,
  communityUpdate: false,
  commentPlaceholder: null,
  passcodecta: null,
  metaTitle: null,
  metaDescription: null,
  subheading: null,
  coverIsMap: false,
  isFeaturedArticle: false,
  isAdultContent: false,
  isLocked: false,
  allowComments: true,
  allowContentCopy: false,
  showInToc: true,
  isEmphasized: false,
  displayAuthor: false,
  displayChildrenUnder: true,
  displayTitle: true,
  displaySheet: false,
  badge: null,
  editURL:
    "https://www.worldanvil.com/world/article/2490bf16-bc70-4de5-9634-5e7d8a227850/edit",
  isEditable: true,
  success: true,
};

export const mockCharacterSheet: CharacterSheet = {
  articleId: mockArticle.id,
  title: mockArticle.title,
  tags: mockArticle.tags?.split(",") || [],
};